language: php

phps:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS gas_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database gas_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS gas_test;'; fi"
  - git submodule update --init
  - cd toopay/gas-orm/third_party/gas/test/travis

script: phpunit --no-globals-backup --configuration $DB.travis.xml